=head1 Welcome to Catalyst

This is the Runtime distribution for the L<Catalyst MVC framework|http://www.catalystframework.org/>.

For more information about Catalyst, write

    perldoc Catalyst

at the command line, or visit http://www.catalystframework.org/.

=head2 Getting Started

1. Install Catalyst if you haven't yet:

    cpanm Catalyst

2. Create a new catalyst application:

    catalyst.pl DemoApp

3. Change the directory to the newly created directory and start the built-in developer server

    cd DemoApp; plackup -Ilib demoapp.psgi

4. Go to http://localhost:5000 and you'll see the default welcome page.

=head2 Resources

You can also install L<Catalyst::Manual|https://metacpan.org/module/Catalyst::Manual> 
from CPAN for more comprehensive information.

If you are going to write your own Catalyst application, you will need to
install L<Catalyst::Devel|https://metacpan.org/module/Catalyst::Devel>.
Afterwards run I<catalyst.pl> for more information about creating your first
app.

=head2 Contributing

If you would like to contribute to Catalyst, please 
L<join us|http://chat.mibbit.com/#catalyst@irc.perl.org> on IRC,
or visit the L<maillist|http://lists.scsys.co.uk/mailman/listinfo/catalyst>.
