=head1 NAME

Catalyst::Manual::FAQ - Frequently Asked Questions

=head1 DESCRIPTION

No questions yet, everything perfect...

=head1 AUTHOR

Sebastian Riedel, C<sri@oook.de>

=head1 COPYRIGHT

This program is free software, you can redistribute it and/or modify it under
the same terms as Perl itself.
