=head1 NAME

Catalyst::Manual::FAQ - Frequently Asked Questions

=head1 DESCRIPTION

Frequently Asked Questions

=head2 How do I regenerate the helper scripts?

Outside your apps dir run the C<catalyst.pl> script with the same name, and the
C<-scripts> switch.

	catalyst.pl -scripts Foo	

To overwrite (instead of creating C<.new> files) use the C<-force> switch.

=head2 I have added tables to my DB - how to autogenerate the classes?

Just run the _create.pl script again with the same parameters, it will ignore
the existing classes and create missing ones based on your DB layout.

=head2 What is the difference between $c->forward and $c->response->redirect?

Forward will modify the flow control and neither reset the context object nor
end the request cycle while a redirect will. See L<Catalyst::Manual::Intro>.

=head2 How can I get rid of those timer comments when using TT as my view?

This config line in MyApp::V::TT will disable this for you:

    __PACKAGE__->config->{CONTEXT} = undef;

=head1 AUTHORS

Sebastian Riedel, C<sri@oook.de>
Danijel Milicevic, C<me@danijel.de>

=head1 COPYRIGHT

This program is free software, you can redistribute it and/or modify it under
the same terms as Perl itself.
