=head1 ROADMAP

This is a living document, that represents the core team's current plans
for the Catalyst framework. It's liable to change at any time. This document
lives in the the catalyst trunk, currently at 

  http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Runtime/5.80/trunk/lib/Catalyst/ROADMAP.pod

Make sure you get it from there to ensure you have the latest version.

=head2 5.80000 1st Quarter 2009

Next major planned release.

=over 4

=item move all inline pod to bottom of file.

=item update pod coverage tests to detect stubbed pod, ensure real coverage

=item Add support for configuration profiles to be selected at startup time
through switches / ENV

=item  Application / Context Split 

Catalyst needs to be split so that $c refers to the current context, and is a separate thing from the Application class.

=item Extend pluggability of the Catalyst core.

good support for reusable components good support for reusable plugins good 
separation of plugins (some reusable components want different plugins) 
near total engine independence

=item Reduce core class data usage.

Refactor everything that doesn't have to be class data into object data

=item Add support for Isotope Engines

This depends on the progress of Isotope

=item Work towards a declarative syntax mode

=back
 
=head2 5.90000 2009

Blue Sky. Will start planning this once we land 5.8 :)

